name: test-java

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test-java:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        java: ["11", "17"]
        include:
          - os: windows-latest
            java: "17"
          - os: macos-latest
            java: "17"

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"

      - run: mvn install
        working-directory: java

      - run: mvn test
        working-directory: java

      - run: ./scripts/check-jar.sh
        working-directory: java
